### ISSUE TITLE
does not compile with mariadb-5.5.44

### ISSUE THREAD

**Issue by naox** [outbrain-inc/audit_login#2]
does not compile with mariadb-5.5.44

```
[ 91%] Building C object plugin/audit_login/CMakeFiles/audit_login.dir/audit_login.c.o
In file included from /root/a/mariadb-5.5.44/include/my_sys.h:20,
                 from /root/a/mariadb-5.5.44/plugin/audit_login/audit_login.c:47:
/root/a/mariadb-5.5.44/include/my_global.h:535: error: redefinition of typedef ‘my_socket’
/root/a/mariadb-5.5.44/include/mysql.h:67: note: previous declaration of ‘my_socket’ was here
In file included from /root/a/mariadb-5.5.44/include/my_sys.h:20,
                 from /root/a/mariadb-5.5.44/plugin/audit_login/audit_login.c:47:
/root/a/mariadb-5.5.44/include/my_global.h:954: error: redefinition of typedef ‘my_ulonglong’
/root/a/mariadb-5.5.44/include/mysql.h:129: note: previous declaration of ‘my_ulonglong’ was here
/root/a/mariadb-5.5.44/include/my_global.h:1014: error: redefinition of typedef ‘my_bool’
/root/a/mariadb-5.5.44/include/mysql.h:51: note: previous declaration of ‘my_bool’ was here
make[2]: *** [plugin/audit_login/CMakeFiles/audit_login.dir/audit_login.c.o] Error 1
make[1]: *** [plugin/audit_login/CMakeFiles/audit_login.dir/all] Error 2
```

**Comment by streaml1ne555** [comment]
Try moving

`#include <my_sys.h>`

Before

`#include <mysql.h>`

That fixed the compile for me with mysql 5.6.23 on FreeBSD. Plugin seems to work without other changes. Not sure about stability though.
